# Generated by Django 4.2 on 2025-03-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
        ('users', '0003_alter_user_email'),
    ]

    operations = [
    ]
