from django.utils import timezone
# ...existing code...

def initiate_payment(request):
    if request.method == 'POST':
        # ...existing code...
        payment = Payment(
            # ...existing fields...
            updated_at=timezone.now()  # Set the updated_at field
        )
        payment.save()
        # ...existing code...
    # ...existing code...
