# Generated by Django 4.2 on 2025-03-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_booking_options_booking_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
